### PR TITLE
Update: Major update to UI and packages

### PR DESCRIPTION
**Pull request by kemiljk**
### Major
* Updates to the new Cosmic SDK, including using the new `media.insertOne()` method

### UI
* UI has been refreshed to support light and dark themes
* UI now uses `Tailwind` classes rather than `Shorti`
* Unsplash logo has been updated to the latest version
* Button layout has been updated and styles improved

### Components
* Multiple components have been extracted into custom components
* Icons are now imported from the Heroicon v2 library as React components
* Div with background image has been replaced with native `img` element
* Button and Input now use native `button` and `input` elements respectively, rather than React's strict components.

### Pages
* Empty State view
* No Results view
* Photos results view

### CODE REVIEW

**Comment by kemiljk** [comment]
@tonyspiro sorry for all the commits, keep spotting little issues. 

Can't seem to correct the viewport scaling problem on mobile. Seems to be CRA issue generally so will need to dig in unless you know a fix.

**Comment by kemiljk** [comment]
It may be a non-issue though as all the logical placements are wider than the default mobile viewport I think.

**Review by tonyspiro — CHANGES_REQUESTED** [review]
Looking good. Couple things:
1. For the default extension width (1,000px wide), let's make it 3 images per row.
2. Align the logos right.

CleanShot 2023-04-25 at 14 45 40@2x

**Comment by kemiljk** [comment]
These issues should be resolved in the latest push

**Comment by tonyspiro** [comment]
Looking good. One more: can we make the images more squared to align more with our dashboard media grid?

**Comment by tonyspiro** [comment]
Also, you can delete the `extension.json` and `extension.zip` files.

**Comment by kemiljk** [comment]
Should be all done now @tonyspiro

**Pull request merged**
